apiVersion: v1
name: apim
# Also update CHANGELOG.md
version: 4.0.0
appVersion: 4.0.0
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim?modal=changelog
  artifacthub.io/changes: |
    - Change the versioning
    - Remove duplicate annotation in ui deployment
    - Add support for managed Service Account for each product
    - Remove old and unused `cache.type` from gateway config map
    - Fix resources missing in ui-deployment.yaml
    - Change readinessProbe for the gateway to sync-process
    - Update Elasticsearch version
    - Allow plugin override via {api|gatewaye}.additionalPlugins property
    - Add auto generate Authorization header on gateway probes when authentication basic is set.
    - Inherit notifiers.smtp from root smtp configuration

