apiVersion: v1
name: apim
# Also update CHANGELOG.md
version: 3.20.13
appVersion: 3.20.13
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim?modal=changelog
  artifacthub.io/changes: |
    - Add attribute `gateway.ssl.keystore.watch` to disable watch of Gateway keystore
    - Fix indentation in `api` section of the Management API and Gateway configmaps
    - Add truststore and keystore attributes to the MongoDB Rate Limit section of the Gateway configmap
    - Update ElasticSearch default version: 3.20.13
